name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd backend
        python -m pytest --cov=. --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        
  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Run tests
      run: |
        cd frontend
        npm test -- --coverage --watchAll=false
        
    - name: Build application
      run: |
        cd frontend
        npm run build
        
  model-validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install ML dependencies
      run: |
        pip install numpy pandas scikit-learn xgboost joblib
        
    - name: Validate model artifacts
      run: |
        python -c "
        import joblib
        import os
        
        # Check if model files exist
        model_files = [
            'ml/models/improved/xgboost_improved_current_best_20250619_172109.pkl',
            'ml/data/processed/final_features.json'
        ]
        
        for file in model_files:
            if os.path.exists(file):
                print(f'✅ {file} exists')
            else:
                print(f'❌ {file} missing')
                exit(1)
        
        # Test model loading
        try:
            model = joblib.load('ml/models/improved/xgboost_improved_current_best_20250619_172109.pkl')
            print('✅ Model loads successfully')
        except Exception as e:
            print(f'❌ Model loading failed: {e}')
            exit(1)
        "
        
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Bandit Security Scan
      run: |
        pip install bandit
        bandit -r backend/ -f json -o bandit-report.json || true
        
    - name: Run npm audit
      run: |
        cd frontend
        npm audit --audit-level high || true